### ISSUE TITLE
Invalid attempt to call FieldCount when reader is closed.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [krmrcn/dapper-dot-net#103]
```
I get this error when running a select query for a mssql table contains 
varchar(MAX) columns with large configuration files in them.  Approximately 15k 
rows.


```

Original issue reported on code.google.com by `kyle.rogers` on 27 Jun 2012 at 6:03

**Comment by GoogleCodeExporter** [comment]
```
Here is the stacktrace. Please let me know if you need any additional 
information.  I'm running the latest version of dapper.

System.InvalidOperationException was unhandled by user code
  Message=Invalid attempt to call FieldCount when reader is closed.
  Source=System.Data
  StackTrace:
       at System.Data.SqlClient.SqlDataReader.get_FieldCount()
       at StackExchange.Profiling.Data.ProfiledDbDataReader.get_FieldCount() in C:\Users\sam\Desktop\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbDataReader.cs:line 37
       at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader) in C:\Dev\dapper-git\Dapper\SqlMapper.cs:line 1689
       at Deserialized34d830d-96d0-4703-96b5-969af8e904ab(IDataReader )
       at Dapper.SqlMapper.<QueryInternal>d__d`1.MoveNext() in C:\Dev\dapper-git\Dapper\SqlMapper.cs:line 603
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\Dev\dapper-git\Dapper\SqlMapper.cs:line 562
       at NetInfo.Audit.Infrastructure.Data.AuditRepository.GetAssets(String sql) in C:\Code\netinfo\NetInfo.Audit\AuditRepository.cs:line 12
       at NetInfo.Audit.Query.IS120Query.Check() in C:\Code\netinfo\NetInfo.Audit\Query\IOSSwitch\IS120Query.cs:line 52
       at NetInfo.Audit.Infrastructure.Controllers.LineItemController.Refresh(String id) in C:\Code\netinfo\NetInfo.Audit\Infrastructure\Controllers\LineItemController.cs:line 55
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
  InnerException: 

```

Original comment by `kyle.rogers` on 27 Jun 2012 at 6:06

**Comment by GoogleCodeExporter** [comment]
```
It was losing the *actual* error message, sorry about that. Fix has been 
committed. Are you using dll or .cs? Meaning: fix has been committed to .cs, 
but I haven't re-deployed to nuget just yet
```

Original comment by `marc.gravell` on 27 Jun 2012 at 6:53
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
Original comment by `marc.gravell` on 27 Jun 2012 at 6:53
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I'm using the dll.
```

Original comment by `kyle.rogers` on 27 Jun 2012 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
ok; 1.10 is deployed to nuget. Let me know how you get on.
```

Original comment by `marc.gravell` on 27 Jun 2012 at 7:22

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `marc.gravell` on 27 Jun 2012 at 8:02
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
i was the same question, but it only occur on the server not the local, what is 
the problem
```

Original comment by `thisili...@gmail.com` on 22 Apr 2013 at 1:47
